### ISSUE TITLE
LinkifiesLocationBar script

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#1]
Glad I’ve looked on your page only some months after [your announcement on Aris’ page](https://github.com/Aris-t2/CustomJSforFx/issues/39) (to use a German idiom: better late then never).

Regarding to the locationbar script:

There’s something wrong with domains and subdomains: Clicking on the domain should open the main domain web page (or the redirect from there), not the subdomain. Clicking on the subdomain should open this subdomain web page, but the latter now leads to an error. If this may help: The addon [breadcrumbus](https://addons.mozilla.org/firefox/addon/breadcrumbus/) ([GitHub resource](https://github.com/jokokko/breadcrumbus)) does it correct. By the way: This even splits sections of the search/query part (separated by `?` and `&`). It lacks only colorization.

Related to this addon: It adds a temporary popup showing the full web address split into clickable parts. Unfortunately, often the original locationbar is too narrow for the full address. Then with your script one cannot click on the later parts like an id anchor (after the hash sign). Maybe you could either mimic the addon behaviour or add an option to use only the colorization part of your script and disable the linking part?

Another thing: I do not like the triangle divider. I was successful in overwriting this to the default slash in my userChrome.css, but perhaps you could provide this as Boolean option?

BTW: If you insist on separate issues for every item from above, let me know.

**Comment by Speravir** [comment]
> Another thing: I do not like the triangle divider. I was successful in overwriting this to the default slash in my userChrome.css

Before someone asks: These are the changes I did
```css
.claseLocationBar span.pathname {
    margin: 0;
    padding-left: 7px;
}
.claseLocationBar .pathname:after {
    content:"/";
    border: 0 none;
    top: 0;
}
```
I’ve also changed the slash colour, but this depends on one’s own taste.

**Comment by sdavidg** [comment]
> 
> 
> > Another thing: I do not like the triangle divider. I was successful in overwriting this to the default slash in my userChrome.css
> 
> Before someone asks: These are the changes I did
> 
> ```css
> .claseLocationBar span.pathname {
>     margin: 0;
>     padding-left: 7px;
> }
> .claseLocationBar .pathname:after {
>     content:"/";
>     border: 0 none;
>     top: 0;
> }
> ```
> 
> I’ve also changed the slash colour, but this depends on one’s own taste.

Great, I'll use that code

**Comment by Speravir** [comment]
Oh, I just noticed this little flaw of mine:
> `border: 0 none;`
Of course, `border: 0;` would be enough.

**Comment by sdavidg** [comment]
> Related to this addon: It adds a temporary popup showing the

You can do rigth-click on the locationbar and then the original locatation bar is shown

> I do not like the triangle divider

Please, try the new version:
```
		pathnameArrow = true,
		fontMonospace = true;
```
