### ISSUE TITLE
Set maximum length for tooltip text

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#10]
As user @Zitronella [yesterday noticed](https://www.camp-firefox.de/forum/thema/137589-firefox-bekommt-tabvorschau/?postID=1244905#post1244905) in forum Camp-Firefox.de (so, text in German) there are cases where a maximum length for the tooltip text would be useful. She provided an example from X (former Twitter), for which, as I have myself noticed in other cases in the past, the whole posting text is copied into the page title and therefore will be exposed in the tooltip.

I’d prefer an option for this (on/off, value of length, 0 for disabling, or whatever in this direction), but I assume the actual setting should be quite easily be possible with CSS, `max-width` and probably some `text-overflow` with `overflow:hidden`. The only thing is that I am in general fine with recent behaviour with breaking the line if the text gets too long. This may get an issue with the proposed setting.

**Comment by sdavidg** [comment]
Edit `numberClampsLines = 0` for use line clamps
