### ISSUE TITLE
tab_title_url competes with Firefox feature, new in Firefox 131

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#11]
Hello, in Firefox 131 there was a new feature added which competes with your script.

At least you should document that the Firefox setting `browser.tabs.hoverPreview.enabled` has to be set to `false`. But perhaps it would be smart to use the now official feature and rewrite the script to be an enhancement of this? To be clear: I am happy, now, with the script as it is.

The two advantages of your script I see in the moment are
* Styling of the web address the same like with [LinkifiesLocationBar](https://github.com/sdavidg/firefoxChromeScripts/blob/main/scripts/dav_LinkifiesLocationBar.uc.js).
* Thumbnail size is adjustable.

**Comment by sdavidg** [comment]
As I said in this report: https://github.com/sdavidg/firefoxChromeScripts/issues/9, the logical thing for the user is to use one of the two systems. I don’t use the preview thumbnail, and I prefer my script. I must write an explanation about this conflict in the README.

Thanks for the report
