### ISSUE TITLE
tab_title_url script

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#2]
The script for tab tooltips has unfortunately some issues:

* Was it intentional that you’ve uploaded the file _without_ the file extension `js`?
* I want to suggest that one can choose the font-family on one’s own. I was successful in managing this by adding the according styles in my userChrome.css, but the hard part here was to get the selector combination for the tooltip label (apparently `#dav_tab_title_url label`). Maybe you should add a short note about this in the script, or you add in the script variables for the font-families. (And the colours, too?) By the way: Why is there in one occurrence `courier` instead of `monospace`?
* Somewhat related: Isn’t the linkify thing rather useless for a tooltip?
* I use this Firefox addon: [Viewhance](https://addons.mozilla.org/firefox/addon/viewhance/) ([GitHub resource](https://github.com/Deathamns/Viewhance)). Among other (IMHO) unrelated things it adds information about the actual media file into the tab label. Alas, with your script this does not work at all, in fact there is no useful tooltip anymore (I see an empty, very small square). First, I wanted to ask you for an array of exemption URLs, for which the script could be disabled, but then I noticed/remembered, that the addon does not add its `moz-extension:` url for most file types (SVG is the [only?] exception, but it does not work with this either.) I get this error in the browser console (profile path shortened, if this matters, it’s a Windows path, but with forward slashes, i.e. `/`):
```
Uncaught URIError: malformed URI sequence
    encodeHTML file:///$profile-path$/chrome/dav_tab_title_url.uc.js:272
    createElement file:///$profile-path$/chrome/dav_tab_title_url.uc.js:289
    createElement file:///$profile-path$/chrome/dav_tab_title_url.uc.js:287
    getTooltipData file:///$profile-path$/chrome/dav_tab_title_url.uc.js:324
    showing file:///$profile-path$/chrome/dav_tab_title_url.uc.js:321
    onpopupshowing chrome://browser/content/browser.xhtml:1
dav_tab_title_url.uc.js:272:10
```
I did not change anything, so the line numbers are the original ones. I actually wonder why I get error messages for `file:` paths, but see nonetheless the original media file url in the locationbar. (Again: SVG is different here, because it gets captured and there is a `moz-extension://$addon-ID$/…` url.)

If you insist on separate issues for every item from above, let me know.

**Comment by sdavidg** [comment]
> Was it intentional that you’ve uploaded the file without the file extension js?

No, it's an error

> Why is there in one occurrence courier instead of monospace? Why is there in one occurrence courier instead of monospace?

Another error

> Isn’t the linkify thing rather useless for a tooltip?

Absolutely, it's just a visual detail. You can change `var linkifiesUrl = true;`

> I want to suggest that one can choose the font-family on one’s own

You can change the font by searching for "font-family" in the code and changing it to whatever you want

> I use this Firefox addon

The problem is the character '%'. I have to do some tests to see how to fix it


Thanks for the report

**Comment by sdavidg** [comment]
Please,  try this file https://github.com/sdavidg/firefoxChromeScripts/blob/main/scripts/dav_tab_title_url.uc.js

**Comment by Speravir** [comment]
> > Isn’t the linkify thing rather useless for a tooltip?
> 
> Absolutely, it's just a visual detail. You can change `var linkifiesUrl = true;`

Ah, it’s for the colours. So, I simply misunderstood this. Actually, I appreciate this feature, especially in combination with the LinkifyLocatiobar script where I use the same colours (or: You’ve already chosen the same colours.)

> You can change the font by searching for "font-family" in the code and changing it to whatever you want

Oh, I already did – in my userChrome.css. It was just a suggestion for an easier adjustment, and with your code changes you made this possible.

Thanks for the update.
