### ISSUE TITLE
Respect punycode setting

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#5]
At least the LinkifiesLocationBar script should respect the Firefox setting `network.IDN_show_punycode`, the default is `false`.

To give some examples:  
I stumbled upon https://www.berühmte-zitate.de/ which is displayed as https://www.xn--berhmte-zitate-isb.de/. While this for a German is guessable it’s different for http://öko.de/ (domain in punycode http://xn--ko-eka.de/) which is (luckily?) not displayed, but redirected to https://www.säfte.com/, though in the address bar I see only the even enigmatic https://www.xn--sfte-loa.com/. For the quite common German surname Müller there are several domains like http://müller.com/ displayed as http://xn--mller-kva.com/.

In parts of the world with non-Latin alphabets there are even full IDN domains, so it would be good to change the script behaviour.

In the moment at least the readable domain is visible if I select the address bar.

The tab_title_url script showing the same behaviour could instead perhaps get an optional setting for a deliberate user choice.

**Comment by sdavidg** [comment]
Good point. Try the new version

**Comment by Speravir** [comment]
Well done!

Now I have to copy this into the tab_title_url script … :-)

(Both scripts share that much code, a combined script would be nice, but, of course, more maintenance work.)

**Comment by sdavidg** [comment]
Thanks for the feedback
