### ISSUE TITLE
dav_tab_title_url.uc.js does not work in Firefox 91

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#6]
With an active `dav_tab_title_url.uc.js` no tab tooltip is shown in Firefox 91 anymore. But if the user script is disabled the tooltip does work – of course without the useful script enhancements, though.

**Comment by sdavidg** [comment]
Thanks for the comment

**Comment by Speravir** [comment]
Thank you, works fine again!
