### ISSUE TITLE
dav_tab_title_url.uc.js

### ISSUE THREAD

**Issue by EstherMoellman** [sdavidg/firefoxChromeScripts#7]
Hi @sdavidg ,

I'm an university student, and I'm part of a small international group of students who like to exchange Firefox CSS customizations for our own personal use (studies and jobs).
We also use several Firefox JavaScripts. But, unfortunately neither I nor anyone in our group knows anything about JavaScript. We use JavaScripts that we find here on Github, or JavaScripts that kindly Devs on Reddit create and adapt for us.

At this moment we need a **simple** JavaScript to show a short tab-title or tab-url inside the urlbar when a tab is mouse-hovered. That's all!
As you know, in vanilla Firefox when a tab is mouse-hovered the **tab tooltip** appears. We want to replace this tab-tooltip, and we want it to appear inside the urlbar. It doesn't matter if the JavaScript uses the tab-tooltip or tab-label or etc, the only thing we need is that when any tab (pinned, unpinned, selected, unselected, active, not active etc)  is mouse-hovered, a short tab-title or short tab-url will appear inside the urlbar. Please @sdavidg , could you help us?

We've already visited all the FF' JavaScripts repos, there is no such script. Also, we have already contacted all the Devs, in the past they always have already helped us a lot with other scripts, but unfortunately at this time we do NOT have anyone to help us. @sdavidg you are our last hope.

Please @sdavidg , I hope you can help us, I don't know if it'll be easy for you to make a JavaScript that shows the short tab-tittle inside the urlbar, but if it's difficult and complex for you, then maybe a modification of your **dav_tab_title_url .uc.js** can work. Anyway, any kind of help from you will be very welcome.

@sdavidg , thank you very much for your time and attention.

**Comment by sdavidg** [comment]
Hi Esther
I don't know how to do that, sorry
