### ISSUE TITLE
dav_button_undoCloseTabs does not work in version 115

### ISSUE THREAD

**Issue by kaos-55** [sdavidg/firefoxChromeScripts#8]
I have been using the dav_button_undoCloseTabs script for a while now, however when upgrading to Firefox version 115 it stopped working. The button no longer displays the closed tab entries.
Attached an image of the problem.
![undoclosetab](https://github.com/sdavidg/firefoxChromeScripts/assets/86812371/003a2de6-e29d-4995-ba3b-7017f3b0059c)

**Comment by sdavidg** [comment]
Thanks for the report

Test the new versión: https://github.com/sdavidg/firefoxChromeScripts/commit/cf49d0a9343ea53ced06b2380dbd8d42caec9017

**Comment by kaos-55** [comment]
Yeah, already fixed for version 115 with the new version of dav_button_undoCloseTabs.uc.js.
Thanks for maintaining the script.
![undoclosetab-fix](https://github.com/sdavidg/firefoxChromeScripts/assets/86812371/1f07f7cf-4e7d-400b-a542-ec79b6f2f54f)
