### ISSUE TITLE
Functionality of tab_title_url will be available by default in Firefox

### ISSUE THREAD

**Issue by Speravir** [sdavidg/firefoxChromeScripts#9]
This is more informational, not thought as actual issue:

According to a report (in German) by Sören Hentzchel (@cadeyrn) Firefox 123 will have integrated tab preview, cf. [Firefox bekommt Tabvorschau](https://www.soeren-hentzschel.at/firefox/firefox-bekommt-tabvorschau/).

So, either this functionality should be integrated into the script or, if conflicting, the original function should be disabled in it.

From what I noticed the script works also on addresses where Firefox does not. Also the optional colorisation of the address parts is a plus of the script, though apparently there is some change for the default Firefox expected, too.

Clues from the report:
* The new function will be disabled by default at least in Firefox 123, because there has more work to be done.
* There are some config settings which could be used to control this new function by the script:
  * `browser.tabs.cardPreview.enabled` (boolean) enables or disables the function.
  * `browser.tabs.cardPreview.showThumbnails` (boolean) controls, whether a tab preview is displayed (like `showPreview` in the user script).
  * `browser.tabs.cardPreview.delayMs` (integer for milliseconds) controls the delay of the tab preview, by default `1000` (like `timeUpdatePreview`?).

**Comment by sdavidg** [comment]
Thanks for the info, I didn't know anything about this.

Anyway, I think the logical thing for the user is to use one of the two systems, I don't think it makes sense to use both at the same time. I will write a note to indicate which configuration needs to be changed.

Thank you
